### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by AR-AStone** [SemlerPDX/OpenAI-VoiceAttack-Plugin#8]
1) run voice command: "Ask ChatGPT"
2) ask something (anything)
Observe:
![image](https://github.com/user-attachments/assets/b5bb4356-106b-4df3-962b-83e9013ebd7f)
![image](https://github.com/user-attachments/assets/0f828f94-3f0a-4ccd-8b20-bf7a8fe685f4)

Latest version of VoiceAttack/OpenAI-VoiceAttack-Plugin. 
Windows 11.

The plaguing is inoperable.

**Comment by felipe-magalhaes-DevCorner** [comment]
Just gotta set the model mate.
I also had the trouble but i looked into source and found that out
![image](https://github.com/user-attachments/assets/f964902a-6de3-44f9-853d-528539d332b6)
![image](https://github.com/user-attachments/assets/ba15bb6a-56d3-4164-b9d6-1d6b8b16c346)

**Comment by felipe-magalhaes-DevCorner** [comment]
Change this
![image](https://github.com/user-attachments/assets/6874500e-e5e9-4028-8713-d0b416358394)![image]
To this (or other options below)

(https://github.com/user-attachments/assets/ad41694a-3af8-4783-a9dd-464eda338de8)
Under the actions of your Ask ChatGPT and Star ChatGPT Session there is a config that you can change, that sets what model to use.
Here are the otions
![image](https://github.com/user-attachments/assets/5031cfc2-cca0-471c-a681-9e0a9245a995)

**Comment by SemlerPDX** [comment]
The default model selected in the included VoiceAttack Sample Profile is `gpt-3.5-turbo-0301` and this should be changed to simply: `gpt-3.5-turbo` or `ChatGPTTurbo` (as you shown in the `OpenAImodels` dictionary code in the second reply here) .... OpenAI has deprecated the `-0301` model, and the standard turbo model refers to the latest iteration of it (as it did when `-0301` was the latest).  These will remain in the codebase and this dictionary (and the included Sample Profile) until I'm able to get the next plugin version out.  I already have an active beta branch but I've not had much time to work on it in awhile.

This was merely an oversight when I created that Sample Profile with this particular default value, a learning experience on how OpenAI presents its models in the API.  In addition to this, the Completion and Dall-E APIs are deprecated, and none of these commands will function in the included Sample Profile or any use of the plugin.  They will be removed from the next version of my plugin altogether.

Everything still functions properly, I use the ChatGPT plugin context daily (many times per day) through my AVCS CHAT profile for VoiceAttack, however I did have to manually change the value of the chosen model in this profile in order to target only `ChatGPTTurbo` and not the `-0301` specific model.

**TL;DNR**
Just use the `ChatGPTTurbo` or `gpt-3.5-turbo` (same thing) and NOT the `ChatGPTTurbo0301` or `gpt-3.5-turbo-0301` model(s).  This still works, so I'm closing this issue as noted and already planned for the next version of the plugin - this version will keep working until that one takes over.
